# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bb6895a36cb7e2581fb5ce52f1f075c307eadfd109ab376a0d8c2ec4048b89839ec423c4e6d74d1416cc655a0798ad697b6ec56942e827e7d11e69f59afd5cc

test:
  secret_key_base: db78ed0c6068c425df8e53100517014bbc5f1babd8109a4fe39705c9ae30752d93a6a60a18a5bb3805ba020133ef002970b5146248d2e165adf7fbdd9a7aafc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
