require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PlayerTransactionsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # PlayerTransaction. As you add validations to PlayerTransaction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlayerTransactionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all player_transactions as @player_transactions" do
      player_transaction = PlayerTransaction.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:player_transactions)).to eq([player_transaction])
    end
  end

  describe "GET show" do
    it "assigns the requested player_transaction as @player_transaction" do
      player_transaction = PlayerTransaction.create! valid_attributes
      get :show, {:id => player_transaction.to_param}, valid_session
      expect(assigns(:player_transaction)).to eq(player_transaction)
    end
  end

  describe "GET new" do
    it "assigns a new player_transaction as @player_transaction" do
      get :new, {}, valid_session
      expect(assigns(:player_transaction)).to be_a_new(PlayerTransaction)
    end
  end

  describe "GET edit" do
    it "assigns the requested player_transaction as @player_transaction" do
      player_transaction = PlayerTransaction.create! valid_attributes
      get :edit, {:id => player_transaction.to_param}, valid_session
      expect(assigns(:player_transaction)).to eq(player_transaction)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PlayerTransaction" do
        expect {
          post :create, {:player_transaction => valid_attributes}, valid_session
        }.to change(PlayerTransaction, :count).by(1)
      end

      it "assigns a newly created player_transaction as @player_transaction" do
        post :create, {:player_transaction => valid_attributes}, valid_session
        expect(assigns(:player_transaction)).to be_a(PlayerTransaction)
        expect(assigns(:player_transaction)).to be_persisted
      end

      it "redirects to the created player_transaction" do
        post :create, {:player_transaction => valid_attributes}, valid_session
        expect(response).to redirect_to(PlayerTransaction.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved player_transaction as @player_transaction" do
        post :create, {:player_transaction => invalid_attributes}, valid_session
        expect(assigns(:player_transaction)).to be_a_new(PlayerTransaction)
      end

      it "re-renders the 'new' template" do
        post :create, {:player_transaction => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested player_transaction" do
        player_transaction = PlayerTransaction.create! valid_attributes
        put :update, {:id => player_transaction.to_param, :player_transaction => new_attributes}, valid_session
        player_transaction.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested player_transaction as @player_transaction" do
        player_transaction = PlayerTransaction.create! valid_attributes
        put :update, {:id => player_transaction.to_param, :player_transaction => valid_attributes}, valid_session
        expect(assigns(:player_transaction)).to eq(player_transaction)
      end

      it "redirects to the player_transaction" do
        player_transaction = PlayerTransaction.create! valid_attributes
        put :update, {:id => player_transaction.to_param, :player_transaction => valid_attributes}, valid_session
        expect(response).to redirect_to(player_transaction)
      end
    end

    describe "with invalid params" do
      it "assigns the player_transaction as @player_transaction" do
        player_transaction = PlayerTransaction.create! valid_attributes
        put :update, {:id => player_transaction.to_param, :player_transaction => invalid_attributes}, valid_session
        expect(assigns(:player_transaction)).to eq(player_transaction)
      end

      it "re-renders the 'edit' template" do
        player_transaction = PlayerTransaction.create! valid_attributes
        put :update, {:id => player_transaction.to_param, :player_transaction => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested player_transaction" do
      player_transaction = PlayerTransaction.create! valid_attributes
      expect {
        delete :destroy, {:id => player_transaction.to_param}, valid_session
      }.to change(PlayerTransaction, :count).by(-1)
    end

    it "redirects to the player_transactions list" do
      player_transaction = PlayerTransaction.create! valid_attributes
      delete :destroy, {:id => player_transaction.to_param}, valid_session
      expect(response).to redirect_to(player_transactions_url)
    end
  end

end
